version: '3.9'
name: 'redis-nbd'

services:
    redis-stack:
        image: redis/redis-stack:6.2.6-v17
        volumes:
            - redis-stack-data:/bitnami/redis/data
        ports:
            - "8001:8001"
            - "6379:6379"
        networks:
            - redisnet
volumes:
    redis-stack-data:
        driver: local

networks:
    redisnet: {}
