/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransactionKafka extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8874628440708668617L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionKafka\",\"namespace\":\"kafka\",\"fields\":[{\"name\":\"amount\",\"type\":[\"null\",{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}]},{\"name\":\"destinationAccount\",\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":[\"null\",\"string\"]},{\"name\":\"sourceAccount\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionKafka> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionKafka> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionKafka> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionKafka> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionKafka> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionKafka to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionKafka from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionKafka instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionKafka fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.math.BigDecimal amount;
  private java.lang.CharSequence destinationAccount;
  private java.lang.CharSequence id;
  private java.lang.CharSequence sourceAccount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionKafka() {}

  /**
   * All-args constructor.
   * @param amount The new value for amount
   * @param destinationAccount The new value for destinationAccount
   * @param id The new value for id
   * @param sourceAccount The new value for sourceAccount
   */
  public TransactionKafka(java.math.BigDecimal amount, java.lang.CharSequence destinationAccount, java.lang.CharSequence id, java.lang.CharSequence sourceAccount) {
    this.amount = amount;
    this.destinationAccount = destinationAccount;
    this.id = id;
    this.sourceAccount = sourceAccount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return amount;
    case 1: return destinationAccount;
    case 2: return id;
    case 3: return sourceAccount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: amount = (java.math.BigDecimal)value$; break;
    case 1: destinationAccount = (java.lang.CharSequence)value$; break;
    case 2: id = (java.lang.CharSequence)value$; break;
    case 3: sourceAccount = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.math.BigDecimal getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.math.BigDecimal value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'destinationAccount' field.
   * @return The value of the 'destinationAccount' field.
   */
  public java.lang.CharSequence getDestinationAccount() {
    return destinationAccount;
  }


  /**
   * Sets the value of the 'destinationAccount' field.
   * @param value the value to set.
   */
  public void setDestinationAccount(java.lang.CharSequence value) {
    this.destinationAccount = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sourceAccount' field.
   * @return The value of the 'sourceAccount' field.
   */
  public java.lang.CharSequence getSourceAccount() {
    return sourceAccount;
  }


  /**
   * Sets the value of the 'sourceAccount' field.
   * @param value the value to set.
   */
  public void setSourceAccount(java.lang.CharSequence value) {
    this.sourceAccount = value;
  }

  /**
   * Creates a new TransactionKafka RecordBuilder.
   * @return A new TransactionKafka RecordBuilder
   */
  public static kafka.TransactionKafka.Builder newBuilder() {
    return new kafka.TransactionKafka.Builder();
  }

  /**
   * Creates a new TransactionKafka RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionKafka RecordBuilder
   */
  public static kafka.TransactionKafka.Builder newBuilder(kafka.TransactionKafka.Builder other) {
    if (other == null) {
      return new kafka.TransactionKafka.Builder();
    } else {
      return new kafka.TransactionKafka.Builder(other);
    }
  }

  /**
   * Creates a new TransactionKafka RecordBuilder by copying an existing TransactionKafka instance.
   * @param other The existing instance to copy.
   * @return A new TransactionKafka RecordBuilder
   */
  public static kafka.TransactionKafka.Builder newBuilder(kafka.TransactionKafka other) {
    if (other == null) {
      return new kafka.TransactionKafka.Builder();
    } else {
      return new kafka.TransactionKafka.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionKafka instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionKafka>
    implements org.apache.avro.data.RecordBuilder<TransactionKafka> {

    private java.math.BigDecimal amount;
    private java.lang.CharSequence destinationAccount;
    private java.lang.CharSequence id;
    private java.lang.CharSequence sourceAccount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(kafka.TransactionKafka.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.amount)) {
        this.amount = data().deepCopy(fields()[0].schema(), other.amount);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.destinationAccount)) {
        this.destinationAccount = data().deepCopy(fields()[1].schema(), other.destinationAccount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.id)) {
        this.id = data().deepCopy(fields()[2].schema(), other.id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.sourceAccount)) {
        this.sourceAccount = data().deepCopy(fields()[3].schema(), other.sourceAccount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionKafka instance
     * @param other The existing instance to copy.
     */
    private Builder(kafka.TransactionKafka other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.amount)) {
        this.amount = data().deepCopy(fields()[0].schema(), other.amount);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.destinationAccount)) {
        this.destinationAccount = data().deepCopy(fields()[1].schema(), other.destinationAccount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.id)) {
        this.id = data().deepCopy(fields()[2].schema(), other.id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sourceAccount)) {
        this.sourceAccount = data().deepCopy(fields()[3].schema(), other.sourceAccount);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.math.BigDecimal getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public kafka.TransactionKafka.Builder setAmount(java.math.BigDecimal value) {
      validate(fields()[0], value);
      this.amount = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public kafka.TransactionKafka.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'destinationAccount' field.
      * @return The value.
      */
    public java.lang.CharSequence getDestinationAccount() {
      return destinationAccount;
    }


    /**
      * Sets the value of the 'destinationAccount' field.
      * @param value The value of 'destinationAccount'.
      * @return This builder.
      */
    public kafka.TransactionKafka.Builder setDestinationAccount(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.destinationAccount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'destinationAccount' field has been set.
      * @return True if the 'destinationAccount' field has been set, false otherwise.
      */
    public boolean hasDestinationAccount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'destinationAccount' field.
      * @return This builder.
      */
    public kafka.TransactionKafka.Builder clearDestinationAccount() {
      destinationAccount = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public kafka.TransactionKafka.Builder setId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public kafka.TransactionKafka.Builder clearId() {
      id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sourceAccount' field.
      * @return The value.
      */
    public java.lang.CharSequence getSourceAccount() {
      return sourceAccount;
    }


    /**
      * Sets the value of the 'sourceAccount' field.
      * @param value The value of 'sourceAccount'.
      * @return This builder.
      */
    public kafka.TransactionKafka.Builder setSourceAccount(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.sourceAccount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sourceAccount' field has been set.
      * @return True if the 'sourceAccount' field has been set, false otherwise.
      */
    public boolean hasSourceAccount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sourceAccount' field.
      * @return This builder.
      */
    public kafka.TransactionKafka.Builder clearSourceAccount() {
      sourceAccount = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionKafka build() {
      try {
        TransactionKafka record = new TransactionKafka();
        record.amount = fieldSetFlags()[0] ? this.amount : (java.math.BigDecimal) defaultValue(fields()[0]);
        record.destinationAccount = fieldSetFlags()[1] ? this.destinationAccount : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.id = fieldSetFlags()[2] ? this.id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sourceAccount = fieldSetFlags()[3] ? this.sourceAccount : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionKafka>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionKafka>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionKafka>
    READER$ = (org.apache.avro.io.DatumReader<TransactionKafka>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.amount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.amount.toString());
    }

    if (this.destinationAccount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.destinationAccount);
    }

    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.id);
    }

    if (this.sourceAccount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.sourceAccount);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.amount = null;
      } else {
        this.amount = new java.math.BigDecimal(in.readString());
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.destinationAccount = null;
      } else {
        this.destinationAccount = in.readString(this.destinationAccount instanceof Utf8 ? (Utf8)this.destinationAccount : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.sourceAccount = null;
      } else {
        this.sourceAccount = in.readString(this.sourceAccount instanceof Utf8 ? (Utf8)this.sourceAccount : null);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.amount = null;
          } else {
            this.amount = new java.math.BigDecimal(in.readString());
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.destinationAccount = null;
          } else {
            this.destinationAccount = in.readString(this.destinationAccount instanceof Utf8 ? (Utf8)this.destinationAccount : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sourceAccount = null;
          } else {
            this.sourceAccount = in.readString(this.sourceAccount instanceof Utf8 ? (Utf8)this.sourceAccount : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










