version: '3.8'

services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
